#!/bin/sh
exec >/dev/null 2>&1
if [ -x /usr/bin/apt ]; then
	/usr/bin/apt update
fi
if [ -x /usr/bin/unattended-upgrade ]; then
	/usr/bin/unattended-upgrade
fi
if [ -x /usr/bin/flatpak ]; then
	/usr/bin/flatpak update --noninteractive -y
	/usr/bin/flatpak uninstall --unused --noninteractive -y
fi
if [ -x /usr/bin/rpi-eeprom-update ]; then
	/usr/bin/rpi-eeprom-update -a
fi
exit 0
