#!/bin/bash
# Geocaching.com - Automatic profile update

basedir="$(dirname "$0")"
[ "${basedir:0:1}" = "/" ] || basedir="$PWD/$basedir"

html_template="$basedir/gcstats.html"

. "$basedir/libgccom.sh"

template_sha1sum()
{
	cat "$html_template" | grep -ve 'Generated by.*</p>' | sha1sum | cut -d' ' -f1
}

old_stats_sha1=
[ -f "$html_template" ] && old_stats_sha1="$(template_sha1sum)"

echo "Generating statistics..."
$GCSTATS --user "$user" --password "$password" -o "$basedir" || \
	die "Failed to generate statistics"
echo

new_stats_sha1="$(template_sha1sum)"
if [ "$new_stats_sha1" = "$old_stats_sha1" ]; then
	echo "Upload not necessary. Profile data unchanged."
else
	echo "Uploading profile..."
	$GCCOM --user "$user" --password "$password" -f "$html_template" --setprofile || \
		die "Failed to upload statistics"
fi

exit 0
