#!/bin/bash
# Geocaching.com - Automatic profile update
set -e

basedir="$(dirname "$0")"
[ "${basedir:0:1}" = "/" ] || basedir="$PWD/$basedir"

GCCOM="$basedir/gccom.py"
GCSTATS="$basedir/gcstats.py"
ACCOUNT="$basedir/account"

user="$(cat "$ACCOUNT" | cut -d ' ' -f 1)"
password="$(cat "$ACCOUNT" | cut -d ' ' -f 2)"


html_template="$basedir/gcstats.html"

template_sha1sum()
{
	cat "$html_template" | grep -ve 'Generated by.*</p>' | sha1sum | cut -d' ' -f1
}

old_stats_sha1=
[ -f "$html_template" ] && old_stats_sha1="$(template_sha1sum)"

echo "Generating statistics..."
$GCSTATS --user "$user" --password "$password" -o "$basedir"
echo

new_stats_sha1="$(template_sha1sum)"
if [ "$new_stats_sha1" = "$old_stats_sha1" ]; then
	echo "Upload not necessary. Profile data unchanged."
else
	echo "Uploading profile..."
	$GCCOM --user "$user" --password "$password" -f "$html_template" --setprofile
fi

