#!/bin/sh
set -e

default_timeout=120
statefile="/tmp/blanking.state"

msg()
{
	[ $quiet -eq 0 ] || return
	local text="$*"
	echo "$text"
	zenity --info --timeout=1 --title="Screen blanking" \
		--text="$text" || true
}

timeout=$default_timeout
quiet=0
[ $# -ge 1 ] && timeout="$1"
[ $# -ge 2 -a "$2" = "quiet" ] && quiet=1
[ "$timeout" = "default" ] && timeout=$default_timeout

do_enable()
{
	local t="$1"
	xset s off
	xset +dpms
	xset dpms 0 0 "$t"
	echo -n "$t" >$statefile
	msg "Turned screen blanking on at $t seconds"
}

do_disable()
{
	xset s off
	xset -dpms
	xset dpms 0 0 0
	rm -f $statefile
	msg "Turned screen blanking off"
}

[ "$timeout" = "toggle" ] && {
	[ -e "$statefile" ] && {
		do_disable
	} || {
		do_enable "$default_timeout"
	}
	exit 0
}
[ "$timeout" = "0" ] && {
	do_disable
	exit 0
}
do_enable "$timeout"
