#!/bin/sh

[ $# -ge 1 ] && [ "$1" = "0" -o "$1" = "off" -o "$1" = "no" ] && {
	# Disable gnash ( switch to flash )
	echo "Switching to flash..."
	exec update-alternatives --set flash-mozilla.so \
		/usr/lib/flashplayer-mozilla/libflashplayer.so
} || {
	# Enable gnash
	echo "Switching to gnash..."
	exec update-alternatives --set flash-mozilla.so \
		/usr/lib/gnash/libgnashplugin.so
}
