#!/bin/sh

command="$1"

lockfile="/run/lock/mixerwrapper.lock"


main_ctl_name()
{
	for c in PCM Master; do
		amixer get "$c" >/dev/null 2>&1 && {
			echo -n "$c"
			return 0
		}
	done
	echo "No master mixer found" 1>&2
	exit 1
}

do_mute_toggle()
{
	( flock -xn 9 || exit 1
		ctl="$(main_ctl_name)"
		amixer set "$ctl" toggle >/dev/null
		sleep 0.5
	) 9>$lockfile
}

do_volume_step_down()
{
	( flock -xn 9 || exit 1
		ctl="$(main_ctl_name)"
		amixer set "$ctl" '5%-' >/dev/null
		sleep 0.15
	) 9>$lockfile
}

do_volume_step_up()
{
	( flock -xn 9 || exit 1
		ctl="$(main_ctl_name)"
		amixer set "$ctl" unmute >/dev/null
		amixer set "$ctl" '5%+' >/dev/null
		sleep 0.15
	) 9>$lockfile
}

case "$command" in
	mute-toggle)
		do_mute_toggle
		;;
	volume-step-down)
		do_volume_step_down
		;;
	volume-step-up)
		do_volume_step_up
		;;
	*)
		echo "Invalid command"
		;;
esac

exit 0
