#!/bin/sh

command="$1"

lockfile="/run/lock/mixerwrapper.lock"


do_lock()
{
	touch "$lockfile"
	flock -x "$lockfile"
}

main_ctl_name()
{
	for c in PCM Master; do
		amixer get "$c" >/dev/null 2>&1 && {
			echo -n "$c"
			return 0
		}
	done
	echo "No master mixer found" 1>&2
	exit 1
}

do_mute_toggle()
{
	do_lock
	ctl="$(main_ctl_name)"
	amixer set "$ctl" toggle
	sleep 0.5
}

do_volume_step_down()
{
	do_lock
	ctl="$(main_ctl_name)"
	amixer set "$ctl" '5%-'
	sleep 0.15
}

do_volume_step_up()
{
	do_lock
	ctl="$(main_ctl_name)"
	echo "CTL=$ctl"
	amixer set "$ctl" unmute
	amixer set "$ctl" '5%+'
	sleep 0.15
}

case "$command" in
	mute-toggle)
		do_mute_toggle
		;;
	volume-step-down)
		do_volume_step_down
		;;
	volume-step-up)
		do_volume_step_up
		;;
	*)
		echo "Invalid command"
		;;
esac

exit 0
