#!/bin/sh

listfile=update-files.list.XXXXXXXX
aria2c_jobs=16

die()
{
	echo "$*" >&2
	exit 1
}

info()
{
	echo "--- $*"
}

usage()
{
	echo "update [OPTIONS]"
	echo
	echo "Options:"
	echo " -p|--parallel          Parallel download"
	echo " -f|--full              Full upgrade"
}

parallel=0
full=0

while [ $# -ge 1 ]; do
	case "$1" in
	-p|--parallel)
		parallel=1
		;;
	-f|--full)
		full=1
		;;
	-h|--help)
		usage
		exit 0
		;;
	*)
		die "Unknown parameter: $1"
		;;
	esac
	shift
done

info "Updating package list"
aptitude update || die "Update failed"

[ $full -eq 0 ] && {
	apt_param="upgrade"
	aptitude_param="safe-upgrade"
} || {
	apt_param="dist-upgrade"
	aptitude_param="full-upgrade"
}

if [ $parallel -ne 0 ]; then
	info "Generating package list for '$aptitude_param'"
	listfile="$(mktemp "$listfile")"
	[ -w "$listfile" ] || die "Failed to create temporary file"
	apt-uri-list $apt_param | apturi2metalink > "$listfile" ||\
		die "Failed to generate file list"

	info "Downloading packages"
	while ! aria2c -j "$aria2c_jobs" -s "$aria2c_jobs" -x "$aria2c_jobs" \
			-t 120 -k 1048576 \
			--retry-wait=1 -d /var/cache/apt/archives/ \
			"$listfile"; do
		sleep 10
	done
	rm "$listfile"
fi

info "Performing '$aptitude_param'"
aptitude $aptitude_param || die "Upgrade failed"

info "Cleaning"
aptitude clean || die "Clean failed"

exit 0
