#!/bin/sh

aria2c_jobs=16
listfile=

die()
{
	echo "$*" >&2
	exit 1
}

info()
{
	echo "--- $*"
}

cleanup()
{
	[ -f "$listfile" ] && {
		rm "$listfile"
		listfile=
	}
}

usage()
{
	echo "update [OPTIONS]"
	echo
	echo "Options:"
	echo " -p|--parallel          Parallel download"
	echo " -f|--full              Full upgrade"
	echo " -d|--download-only     Download only"
}

trap cleanup INT EXIT

parallel=0
full=0
download_only=0

while [ $# -ge 1 ]; do
	case "$1" in
	-p|--parallel)
		parallel=1
		;;
	-f|--full)
		full=1
		;;
	-d|--download-only)
		download_only=1
		;;
	-h|--help)
		usage
		exit 0
		;;
	*)
		die "Unknown parameter: $1"
		;;
	esac
	shift
done

# Be nice
nice=19
renice $nice $$ >/dev/null || echo "Failed to renice to $nice" >&2


[ $full -eq 0 ] && {
	upgrade_mode="upgrade"
} || {
	upgrade_mode="full-upgrade"
}


info "Updating package list"
apt update || die "Update failed"

# Run parallel download, if requested.
if [ $parallel -ne 0 ]; then
	info "Generating package list for '$upgrade_mode'"
	listfile="$(mktemp --tmpdir=/tmp update-files.list.XXXXXXXX)"
	[ -w "$listfile" ] || die "Failed to create temporary file"
	apt-uri-list "$upgrade_mode" | apturi2metalink > "$listfile" ||\
		die "Failed to generate file list"

	info "Downloading packages"
	while ! aria2c -j "$aria2c_jobs" -s "$aria2c_jobs" -x "$aria2c_jobs" \
			-t 120 -k 1048576 \
			--retry-wait=1 -d /var/cache/apt/archives/ \
			"$listfile"; do
		sleep 10
	done
fi

# Do the download and upgrade.
info "Performing '$upgrade_mode'"
dl_flags=
[ $download_only -ne 0 ] && dl_flags="--download-only"
apt $dl_flags --show-upgraded --verbose-versions "$upgrade_mode" ||\
	die "Upgrade failed"

# Exit here, if download only.
[ $download_only -ne 0 ] && exit 0

# Purge packages, if full upgrade.
[ $full -ne 0 ] && {
	info "Purging old packages"
	apt-get autoremove --purge || die "Autoremove failed"
}

info "Cleaning"
apt-get clean || die "Clean failed"

exit 0
