#!/bin/sh

restartfile="/var/run/need-system-restart"

die()
{
	echo "$*" >&2
	exit 1
}

export TERM=linux
export PATH="/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin"

if [ -e "$restartfile" ]; then
	if [ "$1" = "notify" ]; then
		export DISPLAY=:0
		zenity --warning --text "Softwareaktualisierungen wurden installiert.\nBitte starten Sie das System neu."
	else
		shutdown -r now || die "Failed to reboot"
	fi
fi

exit 0
