#!/bin/sh

random="$(hexdump -n 2 -e '/2 "%u"' /dev/urandom)"

for disk in /dev/hd? /dev/sd?; do
	[ -b "$disk" ] || continue
	dd if="$disk" of=/dev/null bs=512 count=1 skip=$random >/dev/null 2>&1
done
